version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=photo_app
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=admin
    ports:
      - '3306:3306'
volumes:
  db:
    driver: local